# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'fm.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QProgressBar, QPushButton, QScrollBar, QSizePolicy,
    QSpinBox, QStatusBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1209, 827)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBoxOnOff = QGroupBox(self.centralwidget)
        self.groupBoxOnOff.setObjectName(u"groupBoxOnOff")
        self.groupBoxOnOff.setGeometry(QRect(10, 9, 120, 161))
        self.pushButtonOn = QPushButton(self.groupBoxOnOff)
        self.pushButtonOn.setObjectName(u"pushButtonOn")
        self.pushButtonOn.setGeometry(QRect(10, 120, 41, 25))
        self.pushButtonOff = QPushButton(self.groupBoxOnOff)
        self.pushButtonOff.setObjectName(u"pushButtonOff")
        self.pushButtonOff.setGeometry(QRect(60, 120, 41, 25))
        self.verticalLayoutWidget_2 = QWidget(self.groupBoxOnOff)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(10, 30, 101, 80))
        self.layoutPower = QVBoxLayout(self.verticalLayoutWidget_2)
        self.layoutPower.setObjectName(u"layoutPower")
        self.layoutPower.setContentsMargins(0, 0, 0, 0)
        self.groupBoxTrackFM = QGroupBox(self.centralwidget)
        self.groupBoxTrackFM.setObjectName(u"groupBoxTrackFM")
        self.groupBoxTrackFM.setGeometry(QRect(140, 9, 761, 161))
        self.verticalLayoutWidget = QWidget(self.groupBoxTrackFM)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 30, 741, 121))
        self.layoutRadioDisplay = QVBoxLayout(self.verticalLayoutWidget)
        self.layoutRadioDisplay.setObjectName(u"layoutRadioDisplay")
        self.layoutRadioDisplay.setContentsMargins(0, 0, 0, 0)
        self.groupBoxStatus = QGroupBox(self.centralwidget)
        self.groupBoxStatus.setObjectName(u"groupBoxStatus")
        self.groupBoxStatus.setGeometry(QRect(912, 10, 281, 251))
        self.label1 = QLabel(self.groupBoxStatus)
        self.label1.setObjectName(u"label1")
        self.label1.setGeometry(QRect(10, 40, 67, 17))
        self.label2 = QLabel(self.groupBoxStatus)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(10, 70, 67, 17))
        self.label3 = QLabel(self.groupBoxStatus)
        self.label3.setObjectName(u"label3")
        self.label3.setGeometry(QRect(10, 100, 67, 17))
        self.label4 = QLabel(self.groupBoxStatus)
        self.label4.setObjectName(u"label4")
        self.label4.setGeometry(QRect(10, 130, 67, 17))
        self.label5 = QLabel(self.groupBoxStatus)
        self.label5.setObjectName(u"label5")
        self.label5.setGeometry(QRect(10, 160, 67, 17))
        self.label6 = QLabel(self.groupBoxStatus)
        self.label6.setObjectName(u"label6")
        self.label6.setGeometry(QRect(10, 190, 67, 17))
        self.label7 = QLabel(self.groupBoxStatus)
        self.label7.setObjectName(u"label7")
        self.label7.setGeometry(QRect(10, 220, 67, 17))
        self.progressBarRSSI = QProgressBar(self.groupBoxStatus)
        self.progressBarRSSI.setObjectName(u"progressBarRSSI")
        self.progressBarRSSI.setGeometry(QRect(80, 40, 118, 23))
        self.progressBarRSSI.setMaximum(255)
        self.progressBarRSSI.setValue(0)
        self.progressBarRSSI.setTextVisible(False)
        self.progressBarSNR = QProgressBar(self.groupBoxStatus)
        self.progressBarSNR.setObjectName(u"progressBarSNR")
        self.progressBarSNR.setGeometry(QRect(80, 70, 118, 23))
        self.progressBarSNR.setMaximum(255)
        self.progressBarSNR.setValue(0)
        self.progressBarSNR.setTextVisible(False)
        self.progressBarMultipath = QProgressBar(self.groupBoxStatus)
        self.progressBarMultipath.setObjectName(u"progressBarMultipath")
        self.progressBarMultipath.setGeometry(QRect(80, 100, 118, 23))
        self.progressBarMultipath.setMaximum(255)
        self.progressBarMultipath.setValue(0)
        self.progressBarMultipath.setTextVisible(False)
        self.progressBarStBlend = QProgressBar(self.groupBoxStatus)
        self.progressBarStBlend.setObjectName(u"progressBarStBlend")
        self.progressBarStBlend.setGeometry(QRect(80, 130, 118, 23))
        self.progressBarStBlend.setValue(24)
        self.progressBarStBlend.setTextVisible(False)
        self.progressBarFrequencyOffset = QProgressBar(self.groupBoxStatus)
        self.progressBarFrequencyOffset.setObjectName(u"progressBarFrequencyOffset")
        self.progressBarFrequencyOffset.setGeometry(QRect(80, 160, 118, 23))
        self.progressBarFrequencyOffset.setMaximum(128)
        self.progressBarFrequencyOffset.setValue(0)
        self.progressBarFrequencyOffset.setTextVisible(False)
        self.progressBarSoftMute = QProgressBar(self.groupBoxStatus)
        self.progressBarSoftMute.setObjectName(u"progressBarSoftMute")
        self.progressBarSoftMute.setGeometry(QRect(80, 190, 118, 23))
        self.progressBarSoftMute.setMaximum(31)
        self.progressBarSoftMute.setValue(0)
        self.progressBarSoftMute.setTextVisible(False)
        self.progressBarHighCut = QProgressBar(self.groupBoxStatus)
        self.progressBarHighCut.setObjectName(u"progressBarHighCut")
        self.progressBarHighCut.setGeometry(QRect(80, 220, 118, 23))
        self.progressBarHighCut.setMaximum(20)
        self.progressBarHighCut.setValue(0)
        self.progressBarHighCut.setTextVisible(False)
        self.labelRSSI = QLabel(self.groupBoxStatus)
        self.labelRSSI.setObjectName(u"labelRSSI")
        self.labelRSSI.setGeometry(QRect(200, 40, 67, 17))
        self.labelSNR = QLabel(self.groupBoxStatus)
        self.labelSNR.setObjectName(u"labelSNR")
        self.labelSNR.setGeometry(QRect(200, 70, 67, 17))
        self.labelMultipath = QLabel(self.groupBoxStatus)
        self.labelMultipath.setObjectName(u"labelMultipath")
        self.labelMultipath.setGeometry(QRect(200, 100, 67, 17))
        self.labelStereoBlend = QLabel(self.groupBoxStatus)
        self.labelStereoBlend.setObjectName(u"labelStereoBlend")
        self.labelStereoBlend.setGeometry(QRect(200, 130, 67, 17))
        self.labelFrequencyOff = QLabel(self.groupBoxStatus)
        self.labelFrequencyOff.setObjectName(u"labelFrequencyOff")
        self.labelFrequencyOff.setGeometry(QRect(200, 160, 67, 17))
        self.labelSoftMute = QLabel(self.groupBoxStatus)
        self.labelSoftMute.setObjectName(u"labelSoftMute")
        self.labelSoftMute.setGeometry(QRect(200, 190, 67, 17))
        self.labelHighCut = QLabel(self.groupBoxStatus)
        self.labelHighCut.setObjectName(u"labelHighCut")
        self.labelHighCut.setGeometry(QRect(200, 220, 67, 17))
        self.groupBoxDeEmphasis = QGroupBox(self.centralwidget)
        self.groupBoxDeEmphasis.setObjectName(u"groupBoxDeEmphasis")
        self.groupBoxDeEmphasis.setGeometry(QRect(10, 180, 120, 81))
        self.comboBoxDeEmphasis = QComboBox(self.groupBoxDeEmphasis)
        self.comboBoxDeEmphasis.setObjectName(u"comboBoxDeEmphasis")
        self.comboBoxDeEmphasis.setGeometry(QRect(10, 30, 101, 31))
        self.groupBoxSeekThreshold = QGroupBox(self.centralwidget)
        self.groupBoxSeekThreshold.setObjectName(u"groupBoxSeekThreshold")
        self.groupBoxSeekThreshold.setGeometry(QRect(140, 180, 111, 81))
        self.spinBoxUpDownSeekThreshold = QSpinBox(self.groupBoxSeekThreshold)
        self.spinBoxUpDownSeekThreshold.setObjectName(u"spinBoxUpDownSeekThreshold")
        self.spinBoxUpDownSeekThreshold.setGeometry(QRect(10, 30, 88, 31))
        self.spinBoxUpDownSeekThreshold.setValue(17)
        self.labelSeekThreshold = QLabel(self.groupBoxSeekThreshold)
        self.labelSeekThreshold.setObjectName(u"labelSeekThreshold")
        self.labelSeekThreshold.setGeometry(QRect(30, 36, 31, 21))
        self.groupBoxSeekTune = QGroupBox(self.centralwidget)
        self.groupBoxSeekTune.setObjectName(u"groupBoxSeekTune")
        self.groupBoxSeekTune.setGeometry(QRect(260, 180, 411, 81))
        self.pushButtonSeekDown = QPushButton(self.groupBoxSeekTune)
        self.pushButtonSeekDown.setObjectName(u"pushButtonSeekDown")
        self.pushButtonSeekDown.setGeometry(QRect(10, 40, 89, 25))
        self.pushButtonTuneDown = QPushButton(self.groupBoxSeekTune)
        self.pushButtonTuneDown.setObjectName(u"pushButtonTuneDown")
        self.pushButtonTuneDown.setGeometry(QRect(110, 40, 89, 25))
        self.pushButtonTuneUp = QPushButton(self.groupBoxSeekTune)
        self.pushButtonTuneUp.setObjectName(u"pushButtonTuneUp")
        self.pushButtonTuneUp.setGeometry(QRect(210, 40, 89, 25))
        self.pushButtonSeekUp = QPushButton(self.groupBoxSeekTune)
        self.pushButtonSeekUp.setObjectName(u"pushButtonSeekUp")
        self.pushButtonSeekUp.setGeometry(QRect(310, 40, 89, 25))
        self.groupBoxFrequency = QGroupBox(self.centralwidget)
        self.groupBoxFrequency.setObjectName(u"groupBoxFrequency")
        self.groupBoxFrequency.setGeometry(QRect(679, 180, 221, 81))
        self.lineEditFrequency = QLineEdit(self.groupBoxFrequency)
        self.lineEditFrequency.setObjectName(u"lineEditFrequency")
        self.lineEditFrequency.setGeometry(QRect(10, 30, 201, 41))
        font = QFont()
        font.setPointSize(25)
        self.lineEditFrequency.setFont(font)
        self.lineEditFrequency.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEditFrequency.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBoxPS = QGroupBox(self.centralwidget)
        self.groupBoxPS.setObjectName(u"groupBoxPS")
        self.groupBoxPS.setGeometry(QRect(10, 270, 241, 111))
        self.lineEditPS = QLineEdit(self.groupBoxPS)
        self.lineEditPS.setObjectName(u"lineEditPS")
        self.lineEditPS.setGeometry(QRect(10, 30, 221, 71))
        self.lineEditPS.setFont(font)
        self.lineEditPS.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBoxRadioText = QGroupBox(self.centralwidget)
        self.groupBoxRadioText.setObjectName(u"groupBoxRadioText")
        self.groupBoxRadioText.setGeometry(QRect(260, 270, 641, 111))
        self.label = QLabel(self.groupBoxRadioText)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 40, 67, 17))
        self.label_2 = QLabel(self.groupBoxRadioText)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 80, 67, 17))
        self.lineEditTextA = QLineEdit(self.groupBoxRadioText)
        self.lineEditTextA.setObjectName(u"lineEditTextA")
        self.lineEditTextA.setGeometry(QRect(90, 30, 541, 31))
        self.lineEditTextB = QLineEdit(self.groupBoxRadioText)
        self.lineEditTextB.setObjectName(u"lineEditTextB")
        self.lineEditTextB.setGeometry(QRect(90, 70, 541, 31))
        self.groupBoxTime = QGroupBox(self.centralwidget)
        self.groupBoxTime.setObjectName(u"groupBoxTime")
        self.groupBoxTime.setGeometry(QRect(912, 270, 281, 91))
        self.lineEditTime = QLineEdit(self.groupBoxTime)
        self.lineEditTime.setObjectName(u"lineEditTime")
        self.lineEditTime.setGeometry(QRect(10, 30, 261, 51))
        font1 = QFont()
        font1.setPointSize(30)
        self.lineEditTime.setFont(font1)
        self.lineEditTime.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBoxPID = QGroupBox(self.centralwidget)
        self.groupBoxPID.setObjectName(u"groupBoxPID")
        self.groupBoxPID.setGeometry(QRect(10, 390, 81, 91))
        self.lineEditPID = QLineEdit(self.groupBoxPID)
        self.lineEditPID.setObjectName(u"lineEditPID")
        self.lineEditPID.setGeometry(QRect(10, 30, 61, 41))
        self.lineEditPID.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBoxPTY = QGroupBox(self.centralwidget)
        self.groupBoxPTY.setObjectName(u"groupBoxPTY")
        self.groupBoxPTY.setGeometry(QRect(100, 390, 151, 91))
        self.lineEditProgramType = QLineEdit(self.groupBoxPTY)
        self.lineEditProgramType.setObjectName(u"lineEditProgramType")
        self.lineEditProgramType.setGeometry(QRect(10, 30, 131, 41))
        font2 = QFont()
        font2.setPointSize(8)
        self.lineEditProgramType.setFont(font2)
        self.lineEditProgramType.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBoxDI = QGroupBox(self.centralwidget)
        self.groupBoxDI.setObjectName(u"groupBoxDI")
        self.groupBoxDI.setGeometry(QRect(260, 390, 591, 91))
        self.lineEditDI = QLineEdit(self.groupBoxDI)
        self.lineEditDI.setObjectName(u"lineEditDI")
        self.lineEditDI.setGeometry(QRect(10, 30, 31, 41))
        self.lineEditDI.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEditStereo = QLineEdit(self.groupBoxDI)
        self.lineEditStereo.setObjectName(u"lineEditStereo")
        self.lineEditStereo.setGeometry(QRect(50, 30, 51, 41))
        self.lineEditStereo.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEditHead = QLineEdit(self.groupBoxDI)
        self.lineEditHead.setObjectName(u"lineEditHead")
        self.lineEditHead.setGeometry(QRect(110, 30, 161, 41))
        self.lineEditHead.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEditCompressed = QLineEdit(self.groupBoxDI)
        self.lineEditCompressed.setObjectName(u"lineEditCompressed")
        self.lineEditCompressed.setGeometry(QRect(280, 30, 151, 41))
        self.lineEditCompressed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEditPTY = QLineEdit(self.groupBoxDI)
        self.lineEditPTY.setObjectName(u"lineEditPTY")
        self.lineEditPTY.setGeometry(QRect(440, 30, 141, 41))
        self.lineEditPTY.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Flags = QGroupBox(self.centralwidget)
        self.Flags.setObjectName(u"Flags")
        self.Flags.setGeometry(QRect(859, 390, 41, 91))
        self.labelTA = QLabel(self.Flags)
        self.labelTA.setObjectName(u"labelTA")
        self.labelTA.setGeometry(QRect(10, 30, 21, 17))
        self.labelTP = QLabel(self.Flags)
        self.labelTP.setObjectName(u"labelTP")
        self.labelTP.setGeometry(QRect(10, 50, 21, 17))
        self.labelMS = QLabel(self.Flags)
        self.labelMS.setObjectName(u"labelMS")
        self.labelMS.setGeometry(QRect(10, 70, 21, 17))
        self.groupBoxDate = QGroupBox(self.centralwidget)
        self.groupBoxDate.setObjectName(u"groupBoxDate")
        self.groupBoxDate.setGeometry(QRect(920, 370, 281, 111))
        self.labelMJD = QLabel(self.groupBoxDate)
        self.labelMJD.setObjectName(u"labelMJD")
        self.labelMJD.setGeometry(QRect(10, 80, 67, 17))
        self.lineEditDate = QLineEdit(self.groupBoxDate)
        self.lineEditDate.setObjectName(u"lineEditDate")
        self.lineEditDate.setGeometry(QRect(10, 30, 261, 31))
        self.lineEditDate.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEditMJD = QLineEdit(self.groupBoxDate)
        self.lineEditMJD.setObjectName(u"lineEditMJD")
        self.lineEditMJD.setGeometry(QRect(70, 70, 81, 31))
        self.lineEditMJD.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBoxPresets = QGroupBox(self.centralwidget)
        self.groupBoxPresets.setObjectName(u"groupBoxPresets")
        self.groupBoxPresets.setGeometry(QRect(10, 580, 891, 91))
        self.checkBoxMemory = QCheckBox(self.groupBoxPresets)
        self.checkBoxMemory.setObjectName(u"checkBoxMemory")
        self.checkBoxMemory.setGeometry(QRect(10, 30, 61, 23))
        self.pushButtonPreset1 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset1.setObjectName(u"pushButtonPreset1")
        self.pushButtonPreset1.setGeometry(QRect(90, 30, 89, 25))
        self.pushButtonPreset2 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset2.setObjectName(u"pushButtonPreset2")
        self.pushButtonPreset2.setGeometry(QRect(190, 30, 89, 25))
        self.pushButtonPreset3 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset3.setObjectName(u"pushButtonPreset3")
        self.pushButtonPreset3.setGeometry(QRect(290, 30, 89, 25))
        self.pushButtonPreset4 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset4.setObjectName(u"pushButtonPreset4")
        self.pushButtonPreset4.setGeometry(QRect(390, 30, 89, 25))
        self.pushButtonPreset5 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset5.setObjectName(u"pushButtonPreset5")
        self.pushButtonPreset5.setGeometry(QRect(490, 30, 89, 25))
        self.pushButtonPreset6 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset6.setObjectName(u"pushButtonPreset6")
        self.pushButtonPreset6.setGeometry(QRect(590, 30, 89, 25))
        self.pushButtonPreset7 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset7.setObjectName(u"pushButtonPreset7")
        self.pushButtonPreset7.setGeometry(QRect(690, 30, 89, 25))
        self.pushButtonPreset8 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset8.setObjectName(u"pushButtonPreset8")
        self.pushButtonPreset8.setGeometry(QRect(790, 30, 89, 25))
        self.pushButtonPreset9 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset9.setObjectName(u"pushButtonPreset9")
        self.pushButtonPreset9.setGeometry(QRect(90, 60, 89, 25))
        self.pushButtonPreset10 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset10.setObjectName(u"pushButtonPreset10")
        self.pushButtonPreset10.setGeometry(QRect(190, 60, 89, 25))
        self.pushButtonPreset11 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset11.setObjectName(u"pushButtonPreset11")
        self.pushButtonPreset11.setGeometry(QRect(290, 60, 89, 25))
        self.pushButtonPreset12 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset12.setObjectName(u"pushButtonPreset12")
        self.pushButtonPreset12.setGeometry(QRect(390, 60, 89, 25))
        self.pushButtonPreset13 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset13.setObjectName(u"pushButtonPreset13")
        self.pushButtonPreset13.setGeometry(QRect(490, 60, 89, 25))
        self.pushButtonPreset14 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset14.setObjectName(u"pushButtonPreset14")
        self.pushButtonPreset14.setGeometry(QRect(590, 60, 89, 25))
        self.pushButtonPreset15 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset15.setObjectName(u"pushButtonPreset15")
        self.pushButtonPreset15.setGeometry(QRect(690, 60, 89, 25))
        self.pushButtonPreset16 = QPushButton(self.groupBoxPresets)
        self.pushButtonPreset16.setObjectName(u"pushButtonPreset16")
        self.pushButtonPreset16.setGeometry(QRect(790, 60, 89, 25))
        self.pushButtonSave = QPushButton(self.groupBoxPresets)
        self.pushButtonSave.setObjectName(u"pushButtonSave")
        self.pushButtonSave.setGeometry(QRect(10, 60, 71, 25))
        self.Volume = QGroupBox(self.centralwidget)
        self.Volume.setObjectName(u"Volume")
        self.Volume.setGeometry(QRect(912, 580, 281, 91))
        self.horizontalScrollBarVolume = QScrollBar(self.Volume)
        self.horizontalScrollBarVolume.setObjectName(u"horizontalScrollBarVolume")
        self.horizontalScrollBarVolume.setGeometry(QRect(10, 30, 241, 20))
        self.horizontalScrollBarVolume.setMaximum(63)
        self.horizontalScrollBarVolume.setOrientation(Qt.Orientation.Horizontal)
        self.checkBoxMono = QCheckBox(self.Volume)
        self.checkBoxMono.setObjectName(u"checkBoxMono")
        self.checkBoxMono.setGeometry(QRect(10, 60, 92, 23))
        self.checkBoxMute = QCheckBox(self.Volume)
        self.checkBoxMute.setObjectName(u"checkBoxMute")
        self.checkBoxMute.setGeometry(QRect(90, 60, 92, 23))
        self.labelVolume = QLabel(self.Volume)
        self.labelVolume.setObjectName(u"labelVolume")
        self.labelVolume.setGeometry(QRect(190, 60, 41, 17))
        self.StatusStrip = QGroupBox(self.centralwidget)
        self.StatusStrip.setObjectName(u"StatusStrip")
        self.StatusStrip.setGeometry(QRect(12, 680, 1181, 80))
        self.toolStripStatusLabel1 = QLabel(self.StatusStrip)
        self.toolStripStatusLabel1.setObjectName(u"toolStripStatusLabel1")
        self.toolStripStatusLabel1.setGeometry(QRect(20, 30, 221, 17))
        self.toolStripStatusLabel2 = QLabel(self.StatusStrip)
        self.toolStripStatusLabel2.setObjectName(u"toolStripStatusLabel2")
        self.toolStripStatusLabel2.setGeometry(QRect(250, 30, 221, 17))
        self.toolStripStatusLabel3 = QLabel(self.StatusStrip)
        self.toolStripStatusLabel3.setObjectName(u"toolStripStatusLabel3")
        self.toolStripStatusLabel3.setGeometry(QRect(480, 30, 211, 20))
        self.toolStripStatusLabel4 = QLabel(self.StatusStrip)
        self.toolStripStatusLabel4.setObjectName(u"toolStripStatusLabel4")
        self.toolStripStatusLabel4.setGeometry(QRect(696, 30, 401, 20))
        self.groupBoxCheck = QGroupBox(self.centralwidget)
        self.groupBoxCheck.setObjectName(u"groupBoxCheck")
        self.groupBoxCheck.setGeometry(QRect(10, 490, 1181, 91))
        self.lineEditBufferOut = QLineEdit(self.groupBoxCheck)
        self.lineEditBufferOut.setObjectName(u"lineEditBufferOut")
        self.lineEditBufferOut.setGeometry(QRect(100, 30, 781, 25))
        self.lineEditBufferIn = QLineEdit(self.groupBoxCheck)
        self.lineEditBufferIn.setObjectName(u"lineEditBufferIn")
        self.lineEditBufferIn.setGeometry(QRect(100, 60, 1071, 25))
        self.lineEditFrequencyValue = QLineEdit(self.groupBoxCheck)
        self.lineEditFrequencyValue.setObjectName(u"lineEditFrequencyValue")
        self.lineEditFrequencyValue.setGeometry(QRect(1052, 30, 121, 25))
        self.lineEditFrequencyValue.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelBufferOut = QLabel(self.groupBoxCheck)
        self.labelBufferOut.setObjectName(u"labelBufferOut")
        self.labelBufferOut.setGeometry(QRect(10, 30, 81, 21))
        self.labelBufferIn = QLabel(self.groupBoxCheck)
        self.labelBufferIn.setObjectName(u"labelBufferIn")
        self.labelBufferIn.setGeometry(QRect(10, 60, 67, 21))
        self.labelFrequencyValue = QLabel(self.groupBoxCheck)
        self.labelFrequencyValue.setObjectName(u"labelFrequencyValue")
        self.labelFrequencyValue.setGeometry(QRect(926, 29, 131, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1209, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.horizontalScrollBarVolume.sliderMoved.connect(self.labelVolume.setNum)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBoxOnOff.setTitle(QCoreApplication.translate("MainWindow", u"On/Off", None))
        self.pushButtonOn.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.pushButtonOff.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.groupBoxTrackFM.setTitle(QCoreApplication.translate("MainWindow", u"Track", None))
        self.groupBoxStatus.setTitle(QCoreApplication.translate("MainWindow", u"Status", None))
        self.label1.setText(QCoreApplication.translate("MainWindow", u"RSSI", None))
        self.label2.setText(QCoreApplication.translate("MainWindow", u"SNR", None))
        self.label3.setText(QCoreApplication.translate("MainWindow", u"Multipath", None))
        self.label4.setText(QCoreApplication.translate("MainWindow", u"ST Blend", None))
        self.label5.setText(QCoreApplication.translate("MainWindow", u"Freq Off", None))
        self.label6.setText(QCoreApplication.translate("MainWindow", u"Soft Mute", None))
        self.label7.setText(QCoreApplication.translate("MainWindow", u"Hi-Cut", None))
        self.labelRSSI.setText(QCoreApplication.translate("MainWindow", u"0 dB\u00b5V", None))
        self.labelSNR.setText(QCoreApplication.translate("MainWindow", u"0 dB", None))
        self.labelMultipath.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.labelStereoBlend.setText(QCoreApplication.translate("MainWindow", u"100%", None))
        self.labelFrequencyOff.setText(QCoreApplication.translate("MainWindow", u"-10 BPPM", None))
        self.labelSoftMute.setText(QCoreApplication.translate("MainWindow", u"0 dB", None))
        self.labelHighCut.setText(QCoreApplication.translate("MainWindow", u"20 Khz", None))
        self.groupBoxDeEmphasis.setTitle(QCoreApplication.translate("MainWindow", u"De-emphasis", None))
        self.groupBoxSeekThreshold.setTitle(QCoreApplication.translate("MainWindow", u"Seek Threshold", None))
        self.labelSeekThreshold.setText(QCoreApplication.translate("MainWindow", u"dB\u00b5V", None))
        self.groupBoxSeekTune.setTitle(QCoreApplication.translate("MainWindow", u"Seek / Tune", None))
        self.pushButtonSeekDown.setText(QCoreApplication.translate("MainWindow", u"Seek Down", None))
        self.pushButtonTuneDown.setText(QCoreApplication.translate("MainWindow", u"Tune Down", None))
        self.pushButtonTuneUp.setText(QCoreApplication.translate("MainWindow", u"Tune Up", None))
        self.pushButtonSeekUp.setText(QCoreApplication.translate("MainWindow", u"Seek Up", None))
        self.groupBoxFrequency.setTitle(QCoreApplication.translate("MainWindow", u"Frequency", None))
        self.groupBoxPS.setTitle(QCoreApplication.translate("MainWindow", u"Program Service", None))
        self.groupBoxRadioText.setTitle(QCoreApplication.translate("MainWindow", u"Radio Text", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Text A", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Text B", None))
        self.groupBoxTime.setTitle(QCoreApplication.translate("MainWindow", u"Time", None))
        self.groupBoxPID.setTitle(QCoreApplication.translate("MainWindow", u"Program ID", None))
        self.groupBoxPTY.setTitle(QCoreApplication.translate("MainWindow", u"Program Type", None))
        self.groupBoxDI.setTitle(QCoreApplication.translate("MainWindow", u"DI Codes", None))
        self.Flags.setTitle(QCoreApplication.translate("MainWindow", u"Flags", None))
        self.labelTA.setText(QCoreApplication.translate("MainWindow", u"TA", None))
        self.labelTP.setText(QCoreApplication.translate("MainWindow", u"TP", None))
        self.labelMS.setText(QCoreApplication.translate("MainWindow", u"MS", None))
        self.groupBoxDate.setTitle(QCoreApplication.translate("MainWindow", u"Date", None))
        self.labelMJD.setText(QCoreApplication.translate("MainWindow", u"MJD", None))
        self.groupBoxPresets.setTitle(QCoreApplication.translate("MainWindow", u"Presets", None))
        self.checkBoxMemory.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.pushButtonPreset1.setText(QCoreApplication.translate("MainWindow", u"#1", None))
        self.pushButtonPreset2.setText(QCoreApplication.translate("MainWindow", u"#2", None))
        self.pushButtonPreset3.setText(QCoreApplication.translate("MainWindow", u"#3", None))
        self.pushButtonPreset4.setText(QCoreApplication.translate("MainWindow", u"#4", None))
        self.pushButtonPreset5.setText(QCoreApplication.translate("MainWindow", u"#5", None))
        self.pushButtonPreset6.setText(QCoreApplication.translate("MainWindow", u"#6", None))
        self.pushButtonPreset7.setText(QCoreApplication.translate("MainWindow", u"#7", None))
        self.pushButtonPreset8.setText(QCoreApplication.translate("MainWindow", u"#8", None))
        self.pushButtonPreset9.setText(QCoreApplication.translate("MainWindow", u"#9", None))
        self.pushButtonPreset10.setText(QCoreApplication.translate("MainWindow", u"#10", None))
        self.pushButtonPreset11.setText(QCoreApplication.translate("MainWindow", u"#11", None))
        self.pushButtonPreset12.setText(QCoreApplication.translate("MainWindow", u"#12", None))
        self.pushButtonPreset13.setText(QCoreApplication.translate("MainWindow", u"#13", None))
        self.pushButtonPreset14.setText(QCoreApplication.translate("MainWindow", u"#14", None))
        self.pushButtonPreset15.setText(QCoreApplication.translate("MainWindow", u"#15", None))
        self.pushButtonPreset16.setText(QCoreApplication.translate("MainWindow", u"#16", None))
        self.pushButtonSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.Volume.setTitle(QCoreApplication.translate("MainWindow", u"Volume", None))
        self.checkBoxMono.setText(QCoreApplication.translate("MainWindow", u"Mono", None))
        self.checkBoxMute.setText(QCoreApplication.translate("MainWindow", u"Mute", None))
        self.labelVolume.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.StatusStrip.setTitle("")
        self.toolStripStatusLabel1.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.toolStripStatusLabel2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.toolStripStatusLabel3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.toolStripStatusLabel4.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.groupBoxCheck.setTitle(QCoreApplication.translate("MainWindow", u"Check", None))
        self.labelBufferOut.setText(QCoreApplication.translate("MainWindow", u"Buffer Out", None))
        self.labelBufferIn.setText(QCoreApplication.translate("MainWindow", u"Buffer In", None))
        self.labelFrequencyValue.setText(QCoreApplication.translate("MainWindow", u"Frequency Value", None))
    # retranslateUi

